# use a cmake image, based on ubuntu:16.04
# see https://hub.docker.com/r/matrim/cmake-examples
image: matrim/cmake-examples

build:
  stage: build
  script:
    - mkdir -p cmake_build
    - cd cmake_build
    - cmake ..
    - make buildtest
  artifacts:
    paths:
      - cmake_build
      # cache outputs to reduce the build time
      cache:
        paths:
          - "cmake_build/*"

# run tests using the binary built before
test:
  stage: test
  script:
    - ./cmake_build/buildtest
