# use a cmake image, based on ubuntu:16.04
# see https://hub.docker.com/r/matrim/cmake-examples
image: matrim/cmake-examples:3.10.2

# cache outputs to reduce the build time
cache:
  paths:
    - "buildus/cmake_build/*"

before_script:
  # update g++ from 5.4 to 8
  - apt update && apt -y install g++-8
  - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100

build:
  stage: build
  script:
    - mkdir -p buildus/cmake_build
    - cd buildus/cmake_build
    - cmake ..
    - make
  artifacts:
    paths:
      - buildtest

# run tests using the binary built before
test:
  stage: test
  script:
    - ./buildus/cmake_build/buildtest
