image: frakma/lab5

stages:
    - build
    - test

build:
    stage: build
    script:
        - apt-get update
        - apt-get install zlib1g-dev
        - cd /
        - wget https://zlib.net/zlib-1.2.11.tar.gz
        - tar -xf zlib-1.2.11.tar.gz
        - cd boost_1_72_0
        - ./b2 --with-iostreams -sZLIB_SOURCE="/zlib-1.2.11"
        - cd $CI_PROJECT_DIR
        - mkdir ./gitus-StartingPoint/build
        - cd ./gitus-StartingPoint/build
        - cmake ..
        - make
    artifacts:
        paths:
            - ./gitus-StartingPoint/build/gitus
            - ./gitus-StartingPoint/build/tests/gittests

test:
    stage: test
    script:
        - ./gitus-StartingPoint/build/tests/gittests