# Use our custom docker image, based on debian
# using gcc (see https://hub.docker.com/_/gcc/), cmake 3.17 and yaml-cpp 0.6.3
image: niko84/yaml-cpp

# cache outputs to reduce the build time
cache:
  paths:
    - "buildus/cmake_build/*"

build:
  stage: build
  script:
    - mkdir -p ./buildus/cmake_build
    - cd buildus/cmake_build
    - cmake ..
    - make
  artifacts:
    paths:
      - ./buildus/cmake_build/tests/buildtests

# run tests using the binary built before
test:
  stage: test
  script:
    - ./buildus/cmake_build/tests/buildtests
