# use a cmake image, based on ubuntu:16.04
# see https://hub.docker.com/r/matrim/cmake-examples
image: matrim/cmake-examples:3.10.2

# cache outputs to reduce the build time
cache:
  paths:
    - "buildus/cmake_build/*"

build:
  stage: build
  script:
    - mkdir -p buildus/cmake_build
    - cd buildus/cmake_build
    - cmake ..
    - make
  artifacts:
    paths:
      - buildtest

# run tests using the binary built before
test:
  stage: test
  script:
    - ./buildus/cmake_build/buildtest
