version: '3'
services:
  orchestrus:
    build: orchestrus/
    depends_on:
      - interface
    ports:
      - "12345:8080"
  interface:
    build: db/
    depends_on:
      - db

  db:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=password