version: '3'
services:
  interface:
    image: "dbinterface"
    ports:
      - "12345:8080"
    depends_on:
      - db

  db:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=password